name: text_selection_controls
description: Create a custom text selection controls on top of the current copy, cut, paste and select all options to use them in your SelectableText or TextField widgets. 
version: 0.0.2
homepage: https://github.com/moneyeSir/flutter_text_selection_controls/tree/master/text_selection_controls
repository: https://github.com/moneyeSir/flutter_text_selection_controls
issue_tracker: https://github.com/moneyeSir/flutter_text_selection_controls/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
